-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "availableStock" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rating" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "taxPercent" DOUBLE PRECISION DEFAULT 0.0;
